name: Downgraded Release

on:
    push:
        tags:
            - '*'

jobs:
    downgrade_release:
        runs-on: ubuntu-latest

        steps:
            -
                uses: "actions/checkout@v2"

            -
                uses: "shivammathur/setup-php@v2"
                with:
                    php-version: 8.2
                    coverage: none

            -   uses: "ramsey/composer-install@v2"

            # downgrade /src to PHP 7.4
            -   run: vendor/bin/rector process src --config build/rector-downgrade-php-74.php --ansi

            # copy PHP 7.4 composer
            -   run: cp build/composer-php-74.json composer.json

            # clear the dev files
            -   run: rm -rf .github .phpcs .scannerwork build tests

            # setup git user
            -
                run: |
                    git config user.email "action@github.com"
                    git config user.name "GitHub Action"

            # publish to the same repository with a new tag
            -
                name: "Tag Downgraded Code"
                run: |
                    git commit -a -m "release PHP 7.4 downgraded ${GITHUB_REF#refs/tags/}"
                    git tag "${GITHUB_REF#refs/tags/}.74"
                    git push origin "${GITHUB_REF#refs/tags/}.74"
